name: CI

on:
  workflow_dispatch:

jobs:
  job1: 
    name: My First Job
    
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.step1.outputs.value1 }}
      output2: ${{ steps.step2.outputs.value1 }}

    steps:
    - id: step1
      name: My First Step
      run: echo "::set-output name=value1::please"
        
    - id: step2
      name: My Second Step
      run: echo "::set-output name=value1::work"
        
  job2:
    name: My Second Job
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} 

