name: SemVer Tagging Example

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  testsemver:

    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run a multi-line script
        run: |
          echo "tag_name - ${{ steps.tag_version.outputs.new_tag }}"
          echo "release_name - Release ${{ steps.tag_version.outputs.new_tag }}"
          echo "body- ${{ steps.tag_version.outputs.changelog }}"
