name: Tell Me A Dad Joke

on:
  workflow_dispatch:

jobs:
  
  GetDadJoke:
    
    runs-on: ubuntu-latest

    
    steps:
     
      - name: Get Dad Joke
        run: |
          JOKE=$(curl -H "Accept: text/plain" https://icanhazdadjoke.com/)
          echo "================================================================="
          echo "$JOKE"
