name: Testing Labels On Issues

on:
  issues:
    types:
      - labeled


jobs:

  testing-issues-label:
    
    runs-on: ubuntu-latest

    steps:

      - name: Output GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo ===========================================
          echo  $GITHUB_CONTEXT

